authentication/urls.py
from django.urls import path, include
from . import views
app_name = 'auth'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from foundation.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('auth/', include('authentication.urls')),
]

authentication/models.py
from django.db import models

# Create your models here.

foundation/models.py
from django.contrib.auth import get_user_model
from typing import Type

from django.contrib.auth.models import AbstractUser
from django.db import models

from foundation import helpers
from foundation.threadinglocals import get_current_user

# Abstract base model for common fields

BaseUser = get_user_model()
class BaseModel(models.Model):
    code = models.CharField(max_length=100, unique=True, blank=False, null=False)
    name = models.CharField(max_length=255, blank=False, null=False)

    created_by = models.ForeignKey(
        BaseUser, on_delete=models.CASCADE, related_name='%(class)s_created',
        blank=True, null=True
    )
    updated_by = models.ForeignKey(
        BaseUser, on_delete=models.CASCADE, related_name='%(class)s_updated',
        blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_active = models.BooleanField(default=True)

    PREFIX = None # To be set in subclasses

    def _generate_code_prefix(self):
        return ''.join([c for c in self.__class__.__name__ if c.isupper()])
    def _get_prefix(self):
        return self.PREFIX or self._generate_code_prefix()

    def save(self, *args, **kwargs):
        current_user: Type[BaseUser] = get_current_user()
        if not self.code:
            self.code = helpers.generate_code(self) # This will also set the ID if it is not set.
        if not self.name:
            self.name = self.code
        if not self.created_by:
            self.created_by = current_user or None
        # Always set updated by
        self.updated_by = current_user or None
        super().save(*args, **kwargs)
    class Meta:
        abstract = True

class Team(BaseModel):
    """
    Represents a team in the system.
    """
    PREFIX = 'TM'
    description = models.CharField(max_length=255, blank=False, null=False)

    def __str__(self):
        return self.name

authentication/forms.py
# Login form
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
class CustomLoginForm(AuthenticationForm):
    """
    Custom login form that inherits from Django's AuthenticationForm.
    """
    username = forms.CharField(
        label='Username',
        max_length=254,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username', 'autofocus': 'autofocus'})
    )
    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'})
    )

authentication/views.py
import logging

from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from packaging.utils import _
from django.contrib.auth import authenticate, login as auth_login
from django.http import HttpResponseRedirect

from authentication.forms import CustomLoginForm

logger = logging.getLogger()

def logout(request):
    """Logout Post request """
    from django.contrib.auth import logout as auth_logout
    auth_logout(request)
    from django.shortcuts import redirect
    return redirect('auth:login')

# Perform login
@require_http_methods(["GET", "POST", "HEAD"])
def login(request):
    """
    Handle the login logic.
    """
    form = CustomLoginForm(data=request.POST or None)
    if request.method == 'POST':
        logger.info('Processing login form submission')
        if form.is_valid():
            logger.info('Form is valid, authenticating user')
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(request.GET.get('next', '/'))
            else:
                logger.warning('Invalid login credentials')
                form.add_error('username', _('Invalid username or password.'))
        else:
            form.add_error('username', _('Invalid username or password.'))
    return render(request, 'authentication/login.html', {'form': form})

foundation/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

@login_required
# Create your views here.
def index(request):
    """
    Render the home page.
    """
    return render(request, 'index.html')

authentication/templates/authentication/login.html
{% extends 'layouts/_base.html' %}
{% load static %}

{% block basecontent %}
    <div class="flex flex-col items-center justify-center px-6 pt-8 mx-auto md:h-screen pt:mt-0 dark:bg-gray-900">
        <div class="flex items-center justify-center gap-4  mb-8 lg:mb-10">
            <a href="{% url 'index' %}"
               class="flex items-center justify-center text-2xl font-semibold dark:text-white">
                <img src="{% static '/images/icon.png' %}" class="mr-4 h-11" alt="FlowBite Logo">
                <span>{{ app_name }}</span>
            </a>
            {% include "layouts/partials/dark-toggle.html" %}
        </div>

        <!-- Card -->
        <div class="w-full max-w-xl p-6 space-y-8 sm:p-8 bg-white rounded-lg shadow dark:bg-gray-800">
            <h2 class="text-2xl font-bold text-gray-900 dark:text-white">
                Sign In
            </h2>
            <form class="mt-8 space-y-6" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {{ form }}
                {#            <div>#}
                {#                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>#}
                {#                <input type="email" name="email" id="email" class="" placeholder="name@company.com" required>#}
                {#            </div>#}
                {#            <div>#}
                {#                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>#}
                {#                <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" required>#}
                {#            </div>#}
                <div class="flex items-start">
                    <div class="flex items-center h-5">
                        <input id="remember" aria-describedby="remember" name="remember" type="checkbox"
                               class="w-4 h-4 border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:focus:ring-primary-600 dark:ring-offset-gray-800 dark:bg-gray-700 dark:border-gray-600">
                    </div>
                    <div class="ml-3 text-sm">
                        <label for="remember" class="font-medium text-gray-900 dark:text-white">Remember me</label>
                    </div>
                    <a href="#" class="ml-auto text-sm text-primary-700 hover:underline dark:text-primary-500">Lost
                        Password?</a>
                </div>
                <button type="submit"
                        class="w-full cursor-pointer px-5 py-3 text-base font-medium text-center text-white bg-primary-700 rounded-lg hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 sm:w-auto dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
                    Login to your account
                </button>
                <div class="text-sm font-medium text-gray-500 dark:text-gray-400">
                    Not registered? <a class="text-primary-700 hover:underline dark:text-primary-500">Create account</a>
                </div>
            </form>
        </div>
    </div>

{% endblock basecontent %}

templates/layouts/_base.html
{% load static %}
{% load django_vite %}

<!DOCTYPE html>
<html lang="en" class="dark">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{{ app_tagline }}">
    <title>HOME - {{ app_name }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
          rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    {% vite_hmr_client %}
    <script>
        // On page load or when changing themes, best to add inline in `head` to avoid FOUC
        if (localStorage.getItem('color-theme') === 'dark' || (!('color-theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark')
        }
    </script>
</head>

<body class="bg-gray-100 dark:bg-gray-900">
<div id="loader" style="position:fixed;top:0;left:0;width:100vw;height:100vh;display:flex;align-items:center;justify-content:center;background:#111;z-index:9999;">
  <svg width="48" height="48" viewBox="0 0 48 48" fill="none" style="display:block" xmlns="http://www.w3.org/2000/svg">
    <circle cx="24" cy="24" r="20" stroke="#fff" stroke-width="4" opacity="0.2"/>
    <path d="M44 24a20 20 0 1 1-20-20" stroke="#fff" stroke-width="4" stroke-linecap="round">
      <animateTransform attributeName="transform" type="rotate" from="0 24 24" to="360 24 24" dur="0.5s" repeatCount="indefinite"/>
    </path>
  </svg>
</div>
{% block basecontent %}
{% endblock basecontent %}

{% vite_asset 'static/src/js/main.js' %}
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.3"></script>
<script>
    window.addEventListener('load', function () {
        document.getElementById('loader').classList.add('hide');
        setTimeout(() => {
            document.getElementById('loader').style.display = 'none';
        }, 300);
    });
</script>
</body>
</html>

templates/layouts/partials/dark-toggle.html
<button id="theme-toggle" data-tooltip-target="tooltip-toggle" type="button"
        class="cursor-pointer text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
    <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 24 24"
         xmlns="http://www.w3.org/2000/svg">
        <path d="M12.3224 5.68708c.2935-.31028.3575-.77266.1594-1.15098-.1981-.37832-.6146-.5891-1.0368-.52467-1.50847.2302-2.93175.83665-4.12869 1.76276-1.19717.92628-2.12732 2.1411-2.69465 3.52702-.56744 1.38619-.75115 2.89299-.53164 4.37079.2195 1.4776.83393 2.8711 1.77895 4.0436.9448 1.1722 2.18683 2.0826 3.60103 2.6449 1.414.5623 2.9539.7584 4.4683.57 1.5145-.1884 2.9549-.7551 4.1784-1.6475 1.2237-.8924 2.1892-2.0806 2.7972-3.4499.1723-.3879.0809-.8423-.2279-1.1335-.3089-.2911-.7679-.3556-1.145-.1608-.8631.4459-1.8291.6799-2.8118.6791h-.0018c-1.1598.0013-2.2925-.3234-3.2596-.931-.9667-.6074-1.7244-1.4697-2.1856-2.4779-.4611-1.0078-.6079-2.1209-.4243-3.20511.1835-1.08442.6905-2.09837 1.4645-2.91681Z"></path>
    </svg>
    <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 24 24"
         xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M13 3a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0V3ZM6.343 4.929A1 1 0 0 0 4.93 6.343l1.414 1.414a1 1 0 0 0 1.414-1.414L6.343 4.929Zm12.728 1.414a1 1 0 0 0-1.414-1.414l-1.414 1.414a1 1 0 0 0 1.414 1.414l1.414-1.414ZM12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm-9 4a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2H3Zm16 0a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2h-2ZM7.757 17.657a1 1 0 1 0-1.414-1.414l-1.414 1.414a1 1 0 1 0 1.414 1.414l1.414-1.414Zm9.9-1.414a1 1 0 0 0-1.414 1.414l1.414 1.414a1 1 0 0 0 1.414-1.414l-1.414-1.414ZM13 19a1 1 0 1 0-2 0v2a1 1 0 1 0 2 0v-2Z"
              clip-rule="evenodd"></path>
    </svg>
    <svg id="theme-toggle-auto-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20"
         xmlns="http://www.w3.org/2000/svg">
        <path d="M3 5a2 2 0 012-2h10a2 2 0 012 2v8H3V5zm-2 10a1 1 0 001 1h16a1 1 0 001-1v-1H1v1zm4-1h10v-8H5v8z"></path>
    </svg>
</button>
<div id="tooltip-toggle" role="tooltip"
     class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip">
    Toggle dark mode
    <div class="tooltip-arrow" data-popper-arrow></div>
</div>

templates/layouts/partials/profile-dropdown.html
<div class="flex items-center ml-3">
    <div>
        <button type="button"
                class="flex cursor-pointer text-sm bg-gray-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
                id="user-menu-button-2" aria-expanded="false" data-dropdown-toggle="dropdown-2">
            <span class="sr-only">Open user menu</span>
            <img class="w-8 h-8 rounded-full"
                 src="https://flowbite.com/docs/images/people/profile-picture-5.jpg" alt="user photo">
        </button>
    </div>
    <!-- Dropdown menu -->
    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600"
         id="dropdown-2">
        <div class="px-4 py-3" role="none">
            <p class="text-sm text-gray-900 dark:text-white" role="none">
                {{ request.user.username }}
            </p>
            <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                {{ request.user.email }}
            </p>
        </div>
        <ul class="py-1" role="none">
            {% if request.user.is_superuser %}
                <li>
                    <a href="{% url 'admin:index' %}"
                       class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
                       role="menuitem">Admin Dashboard</a>
                </li>
            {% endif %}
            <li>
                <a href="{% url 'auth:logout' %}"
                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
                   role="menuitem">Sign out</a>
            </li>
        </ul>
    </div>
</div>

templates/layouts/partials/sidebar-menu-item.html
{% if item.children %}
    <li>
        <button type="button"
                class="sidebar-menu-item group {% if item.active %}menu-item-active{% endif %}"
                aria-controls="dropdown-layouts" data-collapse-toggle="dropdown-layouts">
            {% if item.icon %}
                <i class="{{ item.icon }} flex-shrink-0 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"></i>
            {% endif %}
            <span class="flex-1 ml-3 text-left whitespace-nowrap" sidebar-toggle-item>{{ item.label }}</span>
            <svg sidebar-toggle-item class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                      clip-rule="evenodd"></path>
            </svg>
        </button>
        <ul id="dropdown-layouts" class="hidden py-2 space-y-2">
            {% for child in item.children %}
                {% include "layouts/partials/sidebar-menu-item.html" with item=child %}
            {% endfor %}
        </ul>
    </li>
{% else %}
    <li>
        <a href="{{ item.url }}"
           class="sidebar-menu-item group {% if item.active %}menu-item-active{% endif %}">
            {#            Include icon from item if set #}
            {% if item.icon %}
                <i class="{{ item.icon }} flex-shrink-0 text-gray-500 transition duration-75 group-hover:text-gray-900 dark:text-gray-400 dark:group-hover:text-white"></i>
            {% endif %}
            <span class="ml-3" sidebar-toggle-item>{{ item.label }}</span>
        </a>
    </li>
{% endif %}

templates/layouts/sidebar.html
{% extends "layouts/_base.html" %}
{% block basecontent %}
    <header class="z-99 fixed right-0 left-0 bg-gray-100 dark:bg-gray-950 dark:border-gray-900">
        {% include 'layouts/partials/navbar-main.html' with classes="relative max-w-full mx-auto px-2" %}
    </header>
    <div class="flex pt-20 w-full overflow-hidden">
        {% include 'layouts/partials/sidebar.html' %}
        <div id="main-content"
             class="relative flex-1 w-full h-full lg:ml-70 overflow-y-auto">
            <main class="px-2 max-w-screen-2xl mx-auto w-full">
                {% block content %} {% endblock content %}
            </main>
        </div>
    </div>

{% endblock basecontent %}

templates/layouts/stacked.html
{% extends "layouts/_base.html" %}
{% block basecontent %}
    <header class="left-0 right-0 fixed z-99 bg-secondary-500/90 shadow-xs dark:bg-gray-800 dark:border-gray-900">
        {% include 'layouts/partials/navbar-main.html' with classes="relative max-w-screen-2xl mx-auto" %}
    </header>
    <div class="flex pt-20 overflow-hidden">

        <div id="main-content"
             class="relative w-full max-w-screen-2xl mx-auto h-full overflow-y-auto">
            <main>
                {% block content %} {% endblock content %}
            </main>
        </div>
    </div>
{% endblock basecontent %}